### PR TITLE
Reworked engine sound files.

### PR DESCRIPTION
**Pull request by swampmo**
Reworked engine sounds.

### CODE REVIEW

**Comment by FGDATA** [comment]
@JWocky 
Looks good to me.
Should  I merge?

@IAHM-COL

**Comment by swampmo** [comment]
I'll send a video of the new sound in a minute.

**Comment by swampmo** [comment]
And the C-5. I cleaned it up again too.

**Comment by JWocky** [comment]
Do it, this man knows what he is doing with his sounds! Yay!

**Comment by swampmo** [comment]
Jumbolino https://youtu.be/BQ821D9IdEQ

C-5 as of last night. https://youtu.be/5G9cD63HJIA

And my baby, too bad I can't do modeling to finish the interior.
https://youtu.be/S5f74kR1DNA
 This was a replay, the other two I was trying to fly outside the plane ;)

**Comment by swampmo** [comment]
There has to be a bug in 2016.2 because you can be in a view and it sound
muted then switch through the views back to the same one and it sounds
normal.

**Pull request merged**
